# Generated by Django 4.2.2 on 2023-07-16 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['time', 'name'], 'verbose_name': 'Соискатели', 'verbose_name_plural': 'Соискатели'},
        ),
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(max_length=255, verbose_name='Расскажите о себе'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_pub',
            field=models.BooleanField(default=True, verbose_name='Согласны ли Вы сделать ваше фото доступным другим пользователям?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Добавьте, пожалуйста, Ваше фото'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_content', models.TextField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
